[workspace]
authors = ["Julian Hofer <julianhofer@gnome.org>"]
channels = ["https://prefix.dev/conda-forge"]
name = "advent-of-code-2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
nu = { cmd = "nu day-{{ day }}/part-{{ part }}.nu", args = ["day", "part"] }

[dependencies]
nushell = ">=0.109.0,<0.110"
zig = ">=0.15.2,<0.16"
go = ">=1.25.4,<2"
gopls = ">=0.20.0,<0.21"
