[workspace]
authors = ["Julian Hofer <julianhofer@gnome.org>"]
channels = ["https://prefix.dev/conda-forge"]
name = "advent-of-code-2025"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
nu = { cmd = "nu day-{{ day }}/part-{{ part }}.nu", args = ["day", "part"] }
py = { cmd = "python day-{{ day }}/part-{{ part }}.py", args = ["day", "part"] }


[dependencies]
nushell = ">=0.109.0,<0.110"
python = ">=3.14.0,<3.15"
numpy = ">=2.3.5,<3"
alive-progress = ">=3.2.0,<4"

